# Number Guessing Game
import random

num = random.randint(0, 10)
guesses = 0

userNum = int(input("Guess the number generated by the system(o to 10): "))
while True:
    if userNum < 0 or userNum > 10:
        userNum = int(input("Invalid Input, Please enter from 0 to 10! "))
        guesses += 1
    elif userNum < num:
        userNum = int(input("Too Low, Try Again! "))
        guesses += 1
    elif userNum > num:
        userNum = int(input("Too High, Try Again! "))
        guesses += 1
    else:
        print("CORRECT GUESS!", end=" ")
        break

print(f"The Answer was {num}")
print(f"Number of guesses: {guesses}")